name: "Service Mesh Interface Conformance with Meshery"
description: "Validate SMI specifications using Meshery"
author: "Layer5"
inputs:
  provider_token:
    description: "Provider token to use. NOTE: value of the 'token' key in auth.json"
    required: true
  service_mesh:
    # used for provisioning appropriate meshery-adatper
    description: "SMP compatible name for service mesh to use. e.g: open_service_mesh, istio etc"
    required: true
runs:
  using: "node12"
  main: "main.js"
branding:
  icon: 'check-circle'
  color: 'green'
